[package]
name = "flux-search"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flux-core.workspace = true
flux-fs.workspace = true
grep-matcher = "0.1.9"
grep-regex = "0.1.14"
grep-searcher = "0.1.17"
ignore = "0.4.33"
nucleo = "0.5.0"
unicode-segmentation = "1.13.3"

[dev-dependencies]
tempfile = "3"
